# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-13 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_customer_ckname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='numberofbox',
            field=models.CharField(default='', max_length=100),
        ),
    ]
