# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-13 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_customer_numberofbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='kcity',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
