# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-15 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_customer_kcity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='usn',
            field=models.CharField(default='-', max_length=1000),
        ),
    ]
