# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-12 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ckName',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
